## Numpy

In [ ]:
import numpy as np
# its defined same way as lists and tuples
variable = np.array()

a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Array OPERATIONS

In [2]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5,6,7,8])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# slicing a3D
# It selects elements along the first axis (dimension) of a3D, starting from index 1 up to, but not including, index 3.
print(arr_1d[1:4])  # Slicing elements from index 1 to 3 of arr_1d

# Arithmetic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # Element-wise addition
print(arr1 * arr2)  # Element-wise multiplication

# Reshaping arrays
arr_reshape = arr_1d.reshape(4, 2)  # Reshape arr_1d into a column vector
print(arr_reshape)

# Concatenating arrays
arr_concat = np.concatenate((arr1, arr2))  # Concatenate arr1 and arr2
print(arr_concat)

[2 3 4]
[5 7 9]
[ 4 10 18]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4 5 6]


In [19]:
# Arithmetic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Basic statistics
print(np.mean(arr1))    # Compute mean of arr1
print(np.median(arr2))  # Compute median of arr2
print(np.std(arr1))     # Compute standard deviation of arr1


2.0
5.0
0.816496580927726


In [4]:
# Element-wise operations
arr_exp = np.exp(arr1)  # Exponential of each element in arr1
print(arr_exp)
arr_sqrt = np.sqrt(arr2) # Square root of each element in arr2
print(arr_sqrt)

[ 2.71828183  7.3890561  20.08553692]
[2.         2.23606798 2.44948974]


In [5]:
data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
print(data)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]


In [6]:
import numpy as np

grades = np.array(data)
print(grades)

[50 50 47 97 49  3 53 42 26 74 82 62 37 15 70 27 36 35 48 52 63 64]


In [7]:
print (type(data),'x 2:', data * 2)
print('---')
print (type(grades),'x 2:', grades * 2)

<class 'list'> x 2: [50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64, 50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]
---
<class 'numpy.ndarray'> x 2: [100 100  94 194  98   6 106  84  52 148 164 124  74  30 140  54  72  70
  96 104 126 128]


In [8]:
grades.shape


(22,)

In [9]:
print(grades.mean())
print(grades.std())
print(grades.var())
print(grades.var(axis=0))
print(grades.min())
print(grades.max())


49.18181818181818
21.238122592161233
451.0578512396694
451.0578512396694
3
97


In [10]:
grades.min()

3

In [20]:
# Define an array of study hours
study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,
               13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

# Create a 2D array (an array of arrays)
student_data = np.array([study_hours, grades])

# display the array
student_data

array([[10.  , 11.5 ,  9.  , 16.  ,  9.25,  1.  , 11.5 ,  9.  ,  8.5 ,
        14.5 , 15.5 , 13.75,  9.  ,  8.  , 15.5 ,  8.  ,  9.  ,  6.  ,
        10.  , 12.  , 12.5 , 12.  ],
       [50.  , 50.  , 47.  , 97.  , 49.  ,  3.  , 53.  , 42.  , 26.  ,
        74.  , 82.  , 62.  , 37.  , 15.  , 70.  , 27.  , 36.  , 35.  ,
        48.  , 52.  , 63.  , 64.  ]])

In [12]:
# Show shape of 2D array
student_data.shape

(2, 22)

In [21]:
# Show the first element of the first element
student_data[0][0]
# second element
# student_data[0][1]

10.0

In [14]:
print(student_data)

[[10.   11.5   9.   16.    9.25  1.   11.5   9.    8.5  14.5  15.5  13.75
   9.    8.   15.5   8.    9.    6.   10.   12.   12.5  12.  ]
 [50.   50.   47.   97.   49.    3.   53.   42.   26.   74.   82.   62.
  37.   15.   70.   27.   36.   35.   48.   52.   63.   64.  ]]


In [15]:
# Get the mean value of each sub-array
avg_study = student_data[0].mean()
avg_grade = student_data[1].mean()

print('Average study hours: {:.2f}\nAverage grade: {:.2f}'.format(avg_study, avg_grade))

Average study hours: 10.52
Average grade: 49.18
