In [2]:
import numpy as np

# Create a simple array with integers
simple_array = np.array([1, 2, 3, 4, 5])
print(simple_array)

[1 2 3 4 5]


Creating a 2D array (an array of arrays)


In [ ]:
# Create a 2D array (matrix)
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d_array)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
grades = np.array(data)

study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,
               13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

student_data = np.array([study_hours, grades])

student_data

In [8]:
# Create an array with a range of elements
range_array = np.arange(15)
print(range_array)

# Create an array with a range of floats
float_array = np.arange(2, 10, dtype=float)
print(float_array)

# Create an array with a step size
step_array = np.arange(2, 3, 0.1)
print(step_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [9]:
# Reshape a 1D array to a 3D array
arr = np.arange(36)
reshaped_arr = arr.reshape(3, 4, 3)
print(reshaped_arr)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
